### PR TITLE
Port Trash action button for non-superusers from AOS

### PR DESCRIPTION
**Pull request by adrianbj**

### CODE REVIEW

**Comment by BernhardBaumrock** [comment]
@adrianbj not sure with this one. We have a setting for this in the core! And we have a "Macro" in RockMigrations that enables this setting (I agree it is often useful).

image

So I think if there is a core feature we shouldn't add it to the module to keep things DRY

**Comment by adrianbj** [comment]
Unfortunately I don't think the core setting really does what I want. I don't necessarily want users to have access to the trash, but I don't think they should have to edit a page before they can trash it. This solves that and I assume it's the same reason you added that option to RM, or am I missing something there? And I don't think we should have to install a migration tool to get an admin tweak (which is kinda the whole reason this module has had some life breathed into it, isn't it?)

**Comment by BernhardBaumrock** [comment]
Hey @adrianbj I think this is already in the core - my description might be misleading.

To clarify: 
A "macro" in RockMigrations is not adding any custom code. It just loads/sets/saves something that is already in the core or can be used in the core, or installs a module. So one example is to install tracy, another example is to install DB backups with an opinionated preset. Other than that, the macro does not do anything and the macro is not enabled after you ran it. The checkbox will be non-checked all the time and you can re-run the macro after that, which might make sense or not.

The only thing that my showTrash macro does is it sets this ProcessPageList config setting:
image

Which leads to the trash being visible in the pagelist AND the trash action being available for non-superusers:

image

I think we can get rid of this tweak, no?

**Comment by BernhardBaumrock** [comment]
So I'm not telling you to use RockMigrations instead ;) In RM the macro is just a quality of life improvement to get several defaults for me at once and also to not forget anything...

**Comment by adrianbj** [comment]
Yeah, I figured out what macros did after writing that, but my need still remains the same - trash action button without access to the trash, which I don't think the core can do.

**Comment by jmartsch** [comment]
Thanks for the Tweack. Very useful.

**Pull request merged**
